config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  controller :sessions do
    get  'login'  => :new
    post 'login'  => :create
    get  'logout' => :destroy
  end
  root :to => 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true

  EMAIL_REGEX = /\b[A-Z0-9._%a-z\-\+\']+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,}\z/

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :post

  validates :post,  :presence => true
  validates :name,  :presence => true
  validates :email, :allow_blank => true, :format => { :with => EMAIL_REGEX }
  validates :body,  :presence => true

  scope :with_notifications, -> { where(:notify => true) }

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many   :comments

  validates :user,  :presence => true
  validates :title, :presence => true
  validates :body,  :presence => true

  mount_uploader :attachment, AttachmentUploader

  def author
    user.name
  end

  def comments_count
    comments.count
  end

  def notify_comments
    comments.with_notifications
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :posts

  validates :name,  :presence => true
  validates :email, :presence => true, :uniqueness => true,
    :format => { :with => EMAIL_REGEX }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user

  def logged_in?
    current_user.present?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def log_in_user(user)
    session[:user_id] = user.id
  end

  def log_out_user
    reset_session
  end

  def require_session
    unless logged_in?
      flash[:error] = 'You must be logged in to do that!'
      redirect_to login_url
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :require_session, :only => [:destroy]
  before_action :set_post
  before_action :set_comment, only: [:destroy]

  def create
    @comment = Comment.new(comment_params)
    @comment.post = @post

    if @comment.save!
      notify_users
      redirect_to @post, notice: 'Your comment was added!'
    else
      render @post
    end
  end

  def destroy
    @comment.destroy
    redirect_to post_url(@post), notice: 'Comment was successfully destroyed.'
  end

  private def set_post
    @post = Post.find(params[:post_id])
  end

  private def set_comment
    @comment = Comment.find(params[:id])
  end

  private def comment_params
    params.require(:comment).permit(:name, :email, :body, :notify)
  end

  private def notify_users
    @post.notify_comments.each do |comment|
      CommentMailer.new_comment(comment).deliver unless comment == @comment
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_session, :except => [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.includes(:comments).order(:created_at => :desc)
  end

  def show
    @new_comment = Comment.new(:post => @post)
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private def set_post
    @post = Post.includes(:comments).find(params[:id])
  end

  private def post_params
    params.require(:post).permit(:title, :body, :attachment)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
  end

  def destroy
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :require_session, :only => [:destroy]

  def new
  end

  def create
    if user = User.find_by(:email => params[:email])
      if user.authenticate(params[:password])
        log_in_user(user)
        redirect_to root_url, :notice => "Welcome back #{user.name}."
      else
        flash[:error] = 'Password incorrect.'
        render :new
      end
    else
      flash[:error] = 'Email address not found.'
      render :new
    end
  end

  def destroy
    log_out_user
    redirect_to root_url, :notice => "You've been logged out."
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class
    classes = ['alert']
    if flash[:notice]
      classes << 'alert-success'
    elsif flash[:error]
      classes << 'alert-danger'
    end
    classes.join(' ')
  end

  def flash_message
    flash[:notice] || flash[:error]
  end

  def markdown(text)
    Redcarpet::Markdown.new(Redcarpet::Render::HTML.new).render(text)
  end

end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>" class="comment">
  <header>
    <h5 class="pull-sm-left">
      Comment from
      <% if comment.email %>
        <%= link_to comment.name, "mailto:#{comment.email}" %>
      <% else %>
        <%= comment.name %>
      <% end %>
    </h5>
    <time class="pull-sm-right" datetime="<%= comment.created_at.to_s(:iso8601) %>">
      <%= comment.created_at.strftime('%B %-d, %Y @ %l:%M%P') %>
    </time>
  </header>
  <%= markdown(comment.body).html_safe %>
</div>

app/views/comments/_form.html.erb
<%= form_for([comment.post, comment], :html => { :class => 'comment-form' }) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="form-group">
    <%= f.text_field :name, :class => 'form-control', :placeholder => 'Name (required)' %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.text_field :email, :class => 'form-control', :placeholder => 'Email (optional)' %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.text_area :body, :class => 'form-control', :placeholder => 'Your comment...' %>
  </fieldset>

  <div class="checkbox">
    <label>
      <%= f.check_box :notify, :class => 'form-control' %>
      Notify me of any new comments on this post (email required)
    </label>
  </div>

  <div class="actions">
    <%= f.submit 'Add Comment', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blerg</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body class="<%= controller.controller_name.dasherize %>">
    <div class="container">
      <header class="site-header clearfix">
        <nav>
          <ul class="nav nav-pills pull-xs-right">
            <% if logged_in? %>
              <li class="nav-item">
                <%= link_to 'Logout', logout_path, :class => 'btn btn-sm btn-secondary nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'New Post', new_post_path, :class => 'btn btn-sm btn-success nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Login', login_path, :class => 'btn btn-sm btn-primary nav-link' %>
              </li>
            <% end %>
          </ul>
        </nav>
        <%= image_tag 'logo.png', :alt => 'B!', :class => 'logo' %>
        <h1><%= link_to 'The Blerg', root_path %></h1>
      </header>

      <% if flash.present? %>
        <div class="<%= flash_class %>"><%= flash_message %></div>
      <% end %>

      <main>
        <%= yield %>
      </main>

    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post, :html => { :multipart => true, :class => 'post-form' }) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="form-group">
    <%= f.text_field :title, :class => 'form-control', :placeholder => 'Title' %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.text_area :body, :class => 'form-control', :placeholder => 'Once upon a time...' %>
  </fieldset>

  <fieldset class="form-group">
  <%= f.file_field :attachment, :class => 'form-control' %>
  </fieldset>

  <div class="actions">
    <%= f.submit 'Save Post', :class => 'btn btn-lg btn-primary' %>
    <%= link_to 'Cancel', root_path, :class => 'btn btn-lg btn-secondary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article id="post-<%= post.id %>" class="post">
  <header>
    <h2 class="pull-xs-left"><%= link_to post.title, post %></h2>
    <% if logged_in? %>
      <div class="actions pull-xs-right">
        <%= link_to 'Edit', edit_post_path(post), :class => 'btn btn-sm btn-primary-outline' %>
        <%= link_to 'Delete', post_path(post), :class => 'btn btn-sm btn-danger-outline', :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
      </div>
    <% end %>
    <h3>by <%= post.author %></h3>
  </header>
  <div class="body">
    <%= markdown(post.body).html_safe %>
  </div>
  <% if post.attachment.present? %>
    <%= image_tag post.attachment.url(:large) %>
  <% end %>
  <footer>
    <div class="comment-count pull-sm-left">
      <%= link_to pluralize(post.comments_count, 'comment'), post_path(post, :anchor => 'comments') %>
    </div>

    <div class="posted pull-sm-right">
      Posted
      <time datetime="<%= post.created_at.to_s(:iso8601) %>">
        <%= post.created_at.strftime('%B %-d, %Y @ %l:%M%P') %>
      </time>
    </div>
  </footer>
</article>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<section class="posts">
  <%= render @posts %>
</section>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<%= render @post %>

<section id="comments" class="comments">
  <h3>Comments</h3>
  <% if @post.comments.any? %>
    <%= render @post.comments %>
  <% else %>
    <p class="blank">No comments yet. Be the first!</p>
  <% end %>
</section>

<section class="new-comment">
  <h4>Add a comment</h4>
  <%= render 'comments/form', :comment => @new_comment %>
</section>